### ISSUE TITLE
CommunityPatchLight

### ISSUE THREAD

**Issue by JoKalliauer** [LitzeYT/Settlers4Patch#5]
Ich möchte die Kampangen mit den CommunityPatchLight, der im [Changelog](https://github.com/LitzeYT/Settlers4Patch/blob/master/ChangeLog.md#communitypatchlight-2551527) erwähnt ist, spielen, wie kann ich den Auswählen?

Wenn ich unter dem "Spielen"-Button "History Edition" wähle, habe ich ein Siedlerlimit, wenn ich das Spiel in "Community Patch" öffne kommen wieder Siedler aus den Häusern.

**Comment by LitzeYT** [comment]
Hallo! 
Der Community Patch Light, wurde nun endlich dem Launcher hinzugefügt und steht euch zur Verfügung.
